"""Add API key columns to users

Revision ID: 6a74f7f03d5b
Revises: 97047c57a760
Create Date: 2025-07-20 18:25:48.437980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a74f7f03d5b'
down_revision = '97047c57a760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serpapi_api_key', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('google_maps_api_key', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('google_maps_api_key')
        batch_op.drop_column('serpapi_api_key')

    # ### end Alembic commands ###
