"""Add profile_pic_url and gemini_api_key to User

Revision ID: 97047c57a760
Revises: 
Create Date: 2025-07-15 18:43:40.258379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97047c57a760'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic_url', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('gemini_api_key', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('gemini_api_key')
        batch_op.drop_column('profile_pic_url')

    # ### end Alembic commands ###
